openapi: 3.1.0
info:
  title: LangSmith access_policies settings API
  description: 'The LangSmith API is used to programmatically create and manage LangSmith resources.


    ## Host

    https://api.smith.langchain.com


    ## Authentication

    To authenticate with the LangSmith API, set the `X-Api-Key` header

    to a valid [LangSmith API key](https://docs.langchain.com/langsmith/create-account-api-key#create-an-api-key).


    '
  version: 0.1.0
servers:
- url: /
tags:
- name: settings
paths:
  /api/v1/settings:
    get:
      tags:
      - settings
      summary: Get Settings
      description: Get settings.
      operationId: get_settings_api_v1_settings_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/app__hub__crud__tenants__Tenant'
      security:
      - API Key: []
      - Tenant ID: []
      - Bearer Auth: []
  /api/v1/settings/handle:
    post:
      tags:
      - settings
      summary: Set Tenant Handle
      description: Set tenant handle.
      operationId: set_tenant_handle_api_v1_settings_handle_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetTenantHandleRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/app__hub__crud__tenants__Tenant'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key: []
      - Tenant ID: []
      - Bearer Auth: []
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    app__hub__crud__tenants__Tenant:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        display_name:
          type: string
          title: Display Name
        created_at:
          type: string
          format: date-time
          title: Created At
        tenant_handle:
          anyOf:
          - type: string
          - type: 'null'
          title: Tenant Handle
      type: object
      required:
      - id
      - display_name
      - created_at
      title: Tenant
    SetTenantHandleRequest:
      properties:
        tenant_handle:
          type: string
          title: Tenant Handle
      type: object
      required:
      - tenant_handle
      title: SetTenantHandleRequest
  securitySchemes:
    API Key:
      type: apiKey
      in: header
      name: X-API-Key
    Tenant ID:
      type: apiKey
      in: header
      name: X-Tenant-Id
    Bearer Auth:
      type: http
      description: Bearer tokens are used to authenticate from the UI. Must also specify x-tenant-id or x-organization-id (for org scoped apis).
      scheme: bearer
    Organization ID:
      type: apiKey
      in: header
      name: X-Organization-Id
